name: CI 
on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main 
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: action/checkout@v3
      - uses: action/setup-node@v3
        with:
          node-version: '24'
      - run: npm install
      - run: npm test